Repository camunda-community-hub/pyzeebe, pull requests merged in 2020-10, with the labels that each got.

#63 [ADDED] Ability to add multiple routers at once
  docs/worker_taskrouter.rst
  pyzeebe/worker/worker.py
  tests/unit/worker/worker_test.py
Labels: enhancement

#62 Feature/zeebe grpc package
  Pipfile
  Pipfile.lock
  pyzeebe/grpc_internals/zeebe_adapter_base.py
  pyzeebe/grpc_internals/zeebe_job_adapter.py
  pyzeebe/grpc_internals/zeebe_message_adapter.py
  pyzeebe/grpc_internals/zeebe_pb2.py
  pyzeebe/grpc_internals/zeebe_pb2_grpc.py
  pyzeebe/grpc_internals/zeebe_workflow_adapter.py
  setup.py
  tests/unit/grpc_internals/zeebe_job_adapter_test.py
  tests/unit/grpc_internals/zeebe_message_adapter_test.py
  tests/unit/utils/gateway_mock.py
  tests/unit/utils/grpc_utils.py
Labels: dependencies, enhancement

#65 v2.2.1
  Pipfile
  Pipfile.lock
  docs/conf.py
  docs/worker_taskrouter.rst
  pyzeebe/__init__.py
  pyzeebe/grpc_internals/zeebe_adapter_base.py
  pyzeebe/grpc_internals/zeebe_job_adapter.py
  pyzeebe/grpc_internals/zeebe_message_adapter.py
  pyzeebe/grpc_internals/zeebe_pb2.py
  pyzeebe/grpc_internals/zeebe_pb2_grpc.py
  pyzeebe/grpc_internals/zeebe_workflow_adapter.py
  pyzeebe/worker/worker.py
  setup.py
  tests/unit/grpc_internals/zeebe_job_adapter_test.py
  tests/unit/grpc_internals/zeebe_message_adapter_test.py
  tests/unit/utils/gateway_mock.py
  tests/unit/utils/grpc_utils.py
  tests/unit/worker/worker_test.py
Labels: dependencies, enhancement

#68 Create a logger for the module and use it for logging
  pyzeebe/grpc_internals/zeebe_adapter_base.py
  pyzeebe/grpc_internals/zeebe_job_adapter.py
  pyzeebe/worker/task_handler.py
  pyzeebe/worker/worker.py
  tests/unit/grpc_internals/zeebe_adapter_base_test.py
  tests/unit/worker/task_handler_test.py
Labels: enhancement

#71 Fixed integration tests
  .github/workflows/test-zeebe-integration.yml
Labels: bug, enhancement
